"""Configuration and logging: the two things every other module depends on."""

from faculty_radar.config.logging import (
    JsonFormatter,
    configure_logging,
    get_logger,
    log_settings_banner,
)
from faculty_radar.config.settings import (
    AppSettings,
    CollaborationSettings,
    EmbeddingSettings,
    EvaluationSettings,
    EvidenceSettings,
    ExpertiseSettings,
    IngestionSettings,
    LlmSettings,
    LoggingSettings,
    OpenAlexSettings,
    PathsSettings,
    RagSettings,
    RankingSettings,
    RetrievalSettings,
    ScopeSettings,
    Settings,
    TrendSettings,
    VerificationSettings,
    get_settings,
)

__all__ = [
    "AppSettings",
    "CollaborationSettings",
    "EmbeddingSettings",
    "EvaluationSettings",
    "EvidenceSettings",
    "ExpertiseSettings",
    "IngestionSettings",
    "JsonFormatter",
    "LlmSettings",
    "LoggingSettings",
    "OpenAlexSettings",
    "PathsSettings",
    "RagSettings",
    "RankingSettings",
    "RetrievalSettings",
    "ScopeSettings",
    "Settings",
    "TrendSettings",
    "VerificationSettings",
    "configure_logging",
    "get_logger",
    "get_settings",
    "log_settings_banner",
]
